name: "Dotnet-GithubActions-Example"

on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:  
          JF_URL: https://dhanushvm07.jfrog.io
        with:
          oidc-provider-name: dhanushoidc
          oidc-audience: dhanushoidc

      - name: Configure NuGet Repository
        run: jf dotnet-config --repo-resolve=dhanush-nuget-remote

      - name: Restore dependencies
        run: jf dotnet restore --build-name=my-build-nuget --build-number=${{ github.run_number }}

      - name: Perform Security Audit
        run: jf audit

      - name: Build the project
        run: dotnet pack

      - name: Upload NuGet package to Artifactory
        run: jf rt u "*.nupkg" dhanush-local-nuget --build-name=my-build-nuget --build-number=${{ github.run_number }}

      - name: Collect environment variables
        run: jf rt bce my-build-nuget ${{ github.run_number }}

      - name: Publish Build Info
        run: jf rt bp my-build-nuget ${{ github.run_number }}
